---
service_type: host
addr: 10.10.1.191
hostname: ip-10-10-1-129.eu-central-1.compute.internal
location:
  root: default
  datacenter: DC1
labels:
  - osd
  - mon
  - mgr
---
service_type: host
addr: 10.10.2.162
hostname: ip-10-10-2-162.eu-central-1.compute.internal
location:
  root: default
  datacenter: DC2
labels:
  - osd
  - mon
  - mgr
---
service_type: host
addr: 10.10.3.46
hostname: ip-10-10-3-46.eu-central-1.compute.internal
labels:
  - mon
  - osd
---
service_type: mon
placement:
  label: "mon"
---
service_type: mgr
service_name: mgr
placement:
  label: "mgr"
---
service_type: osd
service_id: all-available-devices
service_name: osd.all-available-devices
placement:
  label: "osd"
spec:
  data_devices:
    all: true
...